/*
   Generated by EX4-TO-MQ4 decompiler LITE V4.0.409.1e [-]
   Website: https://purebeam.biz
   E-mail : purebeam@gmail.com
*/
#property copyright "Copyright @ Rita Lasker"
#property link      "www.ritalasker.com"

#property indicator_chart_window
#property indicator_buffers 6
#property indicator_color1 Red
#property indicator_color2 Blue
#property indicator_color3 Black
#property indicator_color4 Black
#property indicator_color5 Black
#property indicator_color6 Black

int gi_76 = MODE_LWMA;
int gi_80 = 80;
int gi_84 = 5;
string gs_88 = "2010.10.26";
int gi_96 = 31;
double gda_100[];
double gda_104[];
double gda_108[];
double gda_112[];
double gda_116[];
double gda_120[];
int gi_124 = 0;
bool gi_128 = TRUE;

int init() {
   gi_128 = TRUE;
   SetIndexBuffer(0, gda_116);
   SetIndexBuffer(1, gda_120);
   SetIndexStyle(0, DRAW_ARROW, STYLE_DASH);
   SetIndexArrow(0, 159);
   SetIndexStyle(1, DRAW_ARROW, STYLE_DASH);
   SetIndexArrow(1, 159);
   SetIndexDrawBegin(0, 5);
   SetIndexBuffer(2, gda_100);
   SetIndexBuffer(3, gda_104);
   SetIndexBuffer(4, gda_108);
   SetIndexBuffer(5, gda_112);
   SetIndexStyle(2, DRAW_NONE);
   SetIndexStyle(3, DRAW_NONE);
   SetIndexStyle(4, DRAW_NONE);
   SetIndexStyle(5, DRAW_NONE);
   return (0);
}

int deinit() {
   return (0);
}

int start() {
   double ld_0;
   double ld_8;
   double ld_16;
   double ld_24;
   double ld_32;
   double ld_40;
   double ld_48;
   double ld_56;
   double ld_64;
   double ld_72;
   if (!gi_128) return (0);
   if (Bars <= 10) return (0);
   gi_124 = IndicatorCounted();
   if (gi_124 < 0) return (-1);
   if (gi_124 > 0) gi_124--;
   for (int li_80 = Bars - gi_124 - 1; li_80 >= 0; li_80--) {
      ld_0 = iMA(NULL, 0, gi_80, 0, gi_76, PRICE_CLOSE, li_80);
      ld_8 = iMA(NULL, 0, gi_80, 0, gi_76, PRICE_LOW, li_80);
      ld_16 = iMA(NULL, 0, gi_80, 0, gi_76, PRICE_OPEN, li_80);
      ld_24 = iMA(NULL, 0, gi_80, 0, gi_76, PRICE_HIGH, li_80);
      ld_48 = (gda_108[li_80 + 1] + (gda_112[li_80 + 1])) / 2.0;
      ld_72 = (ld_0 + ld_24 + ld_16 + ld_8) / 4.0;
      ld_56 = MathMax(ld_24, MathMax(ld_48, ld_72));
      ld_64 = MathMin(ld_16, MathMin(ld_48, ld_72));
      ld_32 = iMA(NULL, 0, 30, 1, MODE_SMA, PRICE_LOW, li_80);
      ld_40 = iMA(NULL, 0, 30, 1, MODE_SMA, PRICE_LOW, li_80 - 1);
      if (ld_48 < ld_72) {
         gda_100[li_80] = ld_64;
         if (gda_100[li_80] < gda_104[li_80] && gda_100[li_80 + 1] < gda_104[li_80 + 1] && gda_100[li_80 + 2] > gda_104[li_80 + 2]) {
         }
         gda_104[li_80] = ld_56;
      } else {
         gda_100[li_80] = ld_56;
         gda_104[li_80] = ld_64;
         if (gda_100[li_80] > gda_104[li_80] && gda_100[li_80 + 1] > gda_104[li_80 + 1] && gda_100[li_80 + 2] < gda_104[li_80 + 2]) {
         }
      }
      gda_108[li_80] = ld_48;
      gda_112[li_80] = ld_72;
      if (gda_108[li_80] >= gda_112[li_80]) {
         gda_116[li_80] = gda_108[li_80];
         gda_120[li_80] = EMPTY_VALUE;
      } else {
         gda_120[li_80] = gda_112[li_80];
         gda_116[li_80] = EMPTY_VALUE;
      }
   }
   return (0);
}
